# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZjbegIF_pL0b-y9PIXVXP9xlYP0qqh95

1. Line plot
"""

import matplotlib.pyplot as plt

# Data
years = [2018, 2019, 2020, 2021, 2022]
sales = [50, 65, 80, 70, 90]

# Line Plot
plt.plot(years, sales, marker='o')
plt.xlabel("Years")
plt.ylabel("Sales (in lakhs)")
plt.title("Year-wise Sales Growth")
plt.grid(True)

plt.show()

"""2. Bar Chart"""

# Data
subjects = ["Math", "Science", "English", "Computer"]
marks = [88, 75, 92, 95]

# Bar Chart
plt.bar(subjects, marks)
plt.xlabel("Subjects")
plt.ylabel("Marks Obtained")
plt.title("Student Marks in Different Subjects")

plt.show()

"""3. Scatter Plot

"""

# Data
hours_studied = [1, 2, 3, 4, 5, 6, 7, 8]
marks_scored = [40, 45, 50, 55, 60, 70, 75, 85]

# Scatter Plot
plt.scatter(hours_studied, marks_scored)
plt.xlabel("Hours Studied")
plt.ylabel("Marks Scored")
plt.title("Relationship Between Study Hours and Marks")

plt.show()

"""4. Histogram"""

# Data
ages = [18, 19, 20, 21, 22, 22, 23, 23, 24, 25, 25, 25, 26, 27, 28, 28, 29, 30]

# Histogram
plt.hist(ages, bins=5)
plt.xlabel("Age Groups")
plt.ylabel("Frequency")
plt.title("Distribution of Ages in a Group")

plt.show()

